# Generated by Django 3.0.6 on 2020-08-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='email',
        ),
    ]
