# Generated by Django 3.0.6 on 2020-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200802_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscribe_status',
            field=models.IntegerField(choices=[(0, 'not_subscribed'), (1, 'subscribed')], default=0),
        ),
    ]
